# Exercise 5.A 
## NumPy fundamentals
Learning the basics fundamentals of Numpy

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ["apple", "banana", "cherry", "date"]

In [4]:
arr_1 = np.array(["apple", "banna", "cherry", "date"])
print(arr_1)

['apple' 'banna' 'cherry' 'date']


In [7]:
dtype = type(fruits)
print(dtype)  # This shows that the fruits class is in a list

<class 'list'>


In [20]:
arr_2 = np.array([(10, 11, 12),(13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [21]:
print(arr_2.T) # lines data up side by side from left to right

[[10 13]
 [11 14]
 [12 15]]


In [25]:
arr_3 = np.array([(1, 3, 5), (2, 4 , 6)])
print(arr_3.ndim)
print(arr_3.shape)
print(arr_3)

2
(2, 3)
[[1 3 5]
 [2 4 6]]


In [26]:
arr_4 = np.array(arr_3[0, 2])
print(arr_4)

5


In [ ]:
arr_5 = np.array([(1, 1), (1, 1), (1, 1, 1), (1, 1, 1), (1, 1, 1)])
