# # Exercise 1.A NumPy: Manipulating Arrays

In [156]:
import numpy as np

## Looping Through Arrays

In [157]:
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [158]:
for x in arrA:
    x = x * 2
    print(x)

[22 24 26]
[28 30 32]


In [159]:
for y in x:
    y = y * 2
    print(y)

56
60
64


The output in the first syntax displays the two lists doubled while the other one shows then second list doubled.

In [160]:
for x in arrA:
    loop_results = x * 2
    for y in x:
        y = y * 2

In [161]:
print(loop_results) # shows the second list doubled.

[28 30 32]


## Joining and Stacking Arrays

In [162]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [163]:
joined_array_2 = np.concatenate((arrA, arrA), axis = 1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [164]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [165]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2) #ValueError: all input arrays must have the same shape
                           

ValueError: all input arrays must have the same shape

In [ ]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

In [166]:
another_joined_array = np.concatenate((joined_array_1, arrA), axis = 1)
print(another_joined_array) #ValueError: all but the concatenation must match exactly 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [167]:
hey_stack = np.hstack((arrA, arrA)) # Displays the data along the horizon to compare
print(hey_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [168]:
vi_stack = np.vstack((arrA, arrA)) # Displays data vertical 
print(vi_stack)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [169]:
d_stack = np.dstack((arrA, arrA)) # Displays everything in group both groups and separated by a space between the groups
print(d_stack)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [170]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky) #Prints the list as two full separate arrays 

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [171]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino) # This print 3 arrays with the first one showing the full list 
                  # The other two arrays are two halves of the first full array

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [172]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Searching and Replacing Array Values

In [177]:
arrB = np.array([(7, 6),(13, 5),(7, 3)])

sorted_arrB = np.sort(arrB)
print(sorted_arrB)
    

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [179]:
z = np.where(arrB < 7)
arrC = arrB[z]
print(arrC)

[6 5 3]


In [184]:
h = np.where(arrB > 7)
arrD = arrB[h]
print(arrD)

[13]
