# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [4]:
r_1 = np.random.randint(1, 20, size = (1,2))
print(r_1)

[[17  3]]


In [5]:
r_2 = np.random.randint(1, 20, size = (2,1))
print(r_2)

[[ 5]
 [17]]


In [6]:
r_3 = np.random.rand(2,1)
print(r_3)

[[0.21631597]
 [0.22459388]]


In [7]:
r_4 = np.random.randint(20, 100, size = (4, 5))
print(r_4)

[[67 35 82 81 67]
 [97 57 45 44 44]
 [81 50 23 30 35]
 [20 25 51 40 87]]


In [8]:
r_5 = np.random.rand(4,5)
print(r_5)

[[0.0956792  0.77003996 0.82450009 0.2515089  0.77214279]
 [0.39938699 0.52084382 0.1719029  0.9447476  0.8196168 ]
 [0.95821675 0.67422431 0.29589657 0.45292898 0.51752425]
 [0.82571929 0.0826459  0.34533971 0.03718638 0.13276275]]


## Generating Random Choices from an Array

In [15]:
students = np.array(['Jeremiah', 'Brandon', 'Kevin', 'Destiney', 'Edmund', 'Dahlia', 'Hritik', 'Sthefani', 'Luis', 'Natalia'])
call_on = np.random.choice(students)
print(call_on)

Destiney


In [17]:
breakout_groups = np.random.choice(students, size= (3, 4))
print(breakout_groups) # This wouldn't work in reality because as you can see there are repeats of names within the output

[['Edmund' 'Edmund' 'Sthefani' 'Luis']
 ['Natalia' 'Edmund' 'Brandon' 'Natalia']
 ['Brandon' 'Sthefani' 'Destiney' 'Edmund']]


In [27]:
call_on_weighted = np.random.choice(students, p = [0.3, 0, 0.1, 0.1, 0.2, 0, 0.1, 0.1, 0.1, 0], size = (1, 5))
print(call_on_weighted)

# Jeremiah = 30%
# Brandon =  0%
# Kevin = 10%
# Destiney = 10%
# Edmund = 20%
# Dahlia = 0%
# Hritik = 10%
# Sthefani = 10%
# Luis = 10%
# Natalia = 0%

[['Edmund' 'Luis' 'Jeremiah' 'Jeremiah' 'Edmund']]


## Generating a Normal Distribution

In [28]:
bell_curve = np.random.normal(loc= 10, scale = 5, size =(4, 5))
print(bell_curve)

[[16.24777831 12.25141805  8.29453493 11.67881654 10.11214723]
 [13.10861525  8.7266403  12.93385438 10.32525182  4.19842042]
 [11.72784351 17.9787603  10.05453632 17.86196905  5.16867587]
 [ 9.14016629 -0.31667445  7.43980632 15.53066643 18.15176341]]
