# Exercise 1.C Performing operations on arrays

In [2]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 20, size = (1,2))
a = np.array(r_1)

r_2 = np.random.randint(1, 20, size = (2,1))
b = np.array(r_2)

r_3 = np.random.rand(2,1)
c = np.array(r_3)

r_4 = np.random.randint(20, 100, size = (4, 5))
d = np.array(r_4)

r_5 = np.random.rand(4,5)
e = np.array(r_5)

## Permutations

In [4]:
print(d)

[[36 86 64 32 56]
 [66 38 65 32 91]
 [67 34 30 23 93]
 [77 66 73 61 32]]


In [5]:
np.random.shuffle(d)
print(d)

[[66 38 65 32 91]
 [77 66 73 61 32]
 [67 34 30 23 93]
 [36 86 64 32 56]]


### What did it do??
After applying the np.random.shuffle() to variable d,
you can see that data gets shuffled 
vertically by columns  

In [6]:
new_shuffle = np.random.permutation(d)
print(new_shuffle)

[[77 66 73 61 32]
 [36 86 64 32 56]
 [67 34 30 23 93]
 [66 38 65 32 91]]


In [7]:
print(d)

[[66 38 65 32 91]
 [77 66 73 61 32]
 [67 34 30 23 93]
 [36 86 64 32 56]]


### When should I use them??
You should use the shuffle when you want to reorder the sequence but keep the same group.

You should use the permutation when you want to completely randomize the placement of each data point.

In [8]:
print(a)
print(a.shape)
print(b)
print(b.shape)

[[ 1 11]]
(1, 2)
[[13]
 [10]]
(2, 1)


In [9]:
ab = np.add(a,b)
print(ab)
print(ab.shape)

[[14 24]
 [11 21]]
(2, 2)


In [10]:
print(a)
print(a.shape)
print(c)
print(c.shape)

[[ 1 11]]
(1, 2)
[[0.09685902]
 [0.24355695]]
(2, 1)


In [11]:
ac = np.add(a,c)
print(ac)
print(ac.shape)

[[ 1.09685902 11.09685902]
 [ 1.24355695 11.24355695]]
(2, 2)


In [12]:
print(b)
print(b.shape)
print(c)
print(c.shape)


[[13]
 [10]]
(2, 1)
[[0.09685902]
 [0.24355695]]
(2, 1)


In [13]:
bc = np.add(b,c)
print(bc)
print(bc.shape) 

[[13.09685902]
 [10.24355695]]
(2, 1)


In [14]:
try:
    ad = np.add(a,d)
except ValueError:  # Encountered this error name stating it could not broadcast (1,2)(4,5) together
    print("Cannot broadcast (1, 2) (4, 5) together")
else:
    print(ad)
finally:
    print("Try Again")


Cannot broadcast (1, 2) (4, 5) together
Try Again


In [15]:
try:
    cd = np.add(c,d)
except ValueError:
    print("Cannot broadcast (2, 1) (4, 5) together")
else:
    print(cd)


Cannot broadcast (2, 1) (4, 5) together


In [16]:
try:
    bd = np.add(b,d)
except ValueError:
    print("Can't broadcast (2, 1) (4, 5) together")
else:
    print(bd)
    print(bd.shape)
    

Can't broadcast (2, 1) (4, 5) together


In [17]:
print(d)

[[66 38 65 32 91]
 [77 66 73 61 32]
 [67 34 30 23 93]
 [36 86 64 32 56]]


In [18]:
print(np.add(np.array([1]), d)) # Adds 1 values to all variables in the first row

[[67 39 66 33 92]
 [78 67 74 62 33]
 [68 35 31 24 94]
 [37 87 65 33 57]]


In [19]:
print(np.add(np.array([[1]]), d))# Adds 1 value to all variables in the second row

[[67 39 66 33 92]
 [78 67 74 62 33]
 [68 35 31 24 94]
 [37 87 65 33 57]]


In [20]:
print(np.add(np.array([1,1,1,1,1]), d)) # Adds 1 value to all rows

[[67 39 66 33 92]
 [78 67 74 62 33]
 [68 35 31 24 94]
 [37 87 65 33 57]]


In [21]:
print(np.add(np.array([[1],[1]]), d)) # ValueError: Cannot broadcast (2,1) (4,5) together

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

### How does broadcasting and using the add function actually work??

The add function combines an array with another array with the same size, displaying an outcome of both arrays added together. The size needs to be the same size so the values can stay in line with each other. If the arrays conflict in size you will receive an error message saying 
"ValueError: operands could not be broadcast together with shapes (2,1) (4,5)". I like to think of broadcast like making sure everyone has a window to the other side. If the size do not match in arrays not everyone can see.


## Rounding

In [22]:
print(c)

[[0.09685902]
 [0.24355695]]


In [23]:
print(np.trunc(c))

[[0.]
 [0.]]


In [24]:
print(np.fix(c))

[[0.]
 [0.]]


In [25]:
print(np.floor(c))

[[0.]
 [0.]]


In [26]:
print(np.ceil(c))

[[1.]
 [1.]]


In [27]:
print(np.round(c, 2))

[[0.1 ]
 [0.24]]


## Cumulative Operations

In [28]:
print(d)

[[66 38 65 32 91]
 [77 66 73 61 32]
 [67 34 30 23 93]
 [36 86 64 32 56]]


In [29]:
print(np.sum(d))

1122


In [30]:
print(np.sum(d, axis = 0))

[246 224 232 148 272]


In [31]:
print(np.sum(d, axis = 1))

[292 309 247 274]


In [32]:
print(np.cumsum(d))

[  66  104  169  201  292  369  435  508  569  601  668  702  732  755
  848  884  970 1034 1066 1122]


In [33]:
print(np.cumsum(d, axis = 0))

[[ 66  38  65  32  91]
 [143 104 138  93 123]
 [210 138 168 116 216]
 [246 224 232 148 272]]


## Grocery Problem
The first variable represents the
contents of a grocery bag, which contains two vegetables, three fruits, four boxes of
snacks, and no beverages. The second variable represents another grocery bag,
which contains no fruits, four vegetables, two beverages, and one box of snacks.
Assign an appropriate array to each variable that represents how many of each
category of item are in each bag

In [50]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

total_bg1 = np.sum(bag1)
total_bg2 = np.sum(bag2)
both_bg = np.add(total_items_bg1, total_items_bg2)
total_items = np.add(bag1, bag2)


print(f"The first bag contains {total_bg1} items\n"
      f"and the second bag contains {total_bg2} items")
print(f"There are {total_items[0]} vegetables,\n"
      f"{total_items[1]} fruits, {total_items[2]} boxed snacks,\n"
      f"and {total_items[3]} beverages\n"
      f"in both grocery bags")


The first bag contains 9 items
and the second bag contains 7 items
There are 6 vegetables,
3 fruits, 5 boxed snacks,
and 2 beverages
in both grocery bags


## Teamwork
The scenario for this set of
problems is that you are volunteering with a voter registration campaign, and you
have been asked to oversee a squad of door-knockers. There are three people on
your team: Ali, Ben, and Carla. Your squad went out to knock on doors each evening
last week, Monday through Friday, and now you are assembling that data

In [56]:
Ali = np.array([5, 4, 6, 4, 2])
Ben = np.array([0, 5, 5, 3, 4])
Carla = np.array([3, 6, 0, 3, 4])

all_knocks = np.sum([Ali, Ben, Carla])

print(all_knocks)

54


In [59]:
per_person = np.divide(all_knocks, 3)
print(f"In the group there were {all_knocks} knocks in total \n"
      f"with {int(per_person)} knocks per person")

In the group there were 54 knocks in total 
with 18 knocks per person


The organization you’re working with estimates that for every two door-knocks, one
of those people will actually turn out to vote. For your report to the organization,
what is the rolling total of estimated votes that your group was able to turn out, day
by day for last week

In [66]:
all_knoc = np.add(Ali, Ben, Carla)
voters = np.divide(all_knoc, 2)
print_results = np.cumsum(voters)

print(np.ceil(print_results))

[ 3.  7. 13. 16. 19.]
